### ISSUE TITLE
Fixing Master

### ISSUE THREAD

**Issue by RowAtk** [Kayon-Marie/SMPL_Interpreter#16]
General needed changes due to misconceptions by the team from the spec.
There was confusion about:
- what is a statement vs an expression?
- what is an assignment vs definition?

Based on talks:
A statement is a expression that return value is not used as input for another expression. Statements are terminated with a ";"

A definition is the creation of a new id and value pairing in an environment. 
> Syntax: def var value;

An assignment is providing a new value for an existing id in the environment. If the id doesn't exist, assignment should fail. that is the main difference.
Assuming variable "x" exists in environment:
> Syntax: x := 5;

ALSO:
- negation of expressions is at a term level which could be incorrect.
- Generated java files still in working commits
- Statements is not abstract and doesn't enforce implementation of visit() and toString() to children. unlike Exp.

**Comment by GalenHare** [comment]
Was this resolved?

**Comment by RowAtk** [comment]
Yeah
